name: Release New Version

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number (e.g. 1.2.3)"
        required: true
        type: string

permissions:
  contents: write # required for creating releases

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            artifact_name: openpyxl_mcp_server.exe
          - os: macos-latest
            artifact_name: openpyxl_mcp_server

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Build executable
        run: |
          pyinstaller openpyxl_mcp_server.spec

      - name: Sign macOS executable
        if: matrix.os == 'macos-latest'
        run: |
          codesign --force --deep --sign - dist/openpyxl_mcp_server

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: ./dist/${{ matrix.artifact_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: openpyxl_mcp_server.exe
          path: ./dist

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: openpyxl_mcp_server
          path: ./dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ inputs.version }}
          release_name: v${{ inputs.version }}
          draft: false
          prerelease: false

      - name: Upload Windows Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/openpyxl_mcp_server.exe
          asset_name: openpyxl_mcp_server.exe
          asset_content_type: application/octet-stream

      - name: Upload macOS Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/openpyxl_mcp_server
          asset_name: openpyxl_mcp_server
          asset_content_type: application/octet-stream
